version: '3'
services:
        web:
                image: holiday
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8206:8206"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
